image: node:13.7.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

before_script:
- npm install

cache:
  paths:
    - node_modules/

lint:
  script:
    - npm run lint

test:
  script:
    - npm run build
    - npm run test

release:
  only:
    - tags
  script:
    - npm run build
  artifacts:
    paths:
      - dist/src

pages:
  stage: deploy
  script:
    - npm run doc
    - mkdir -p public
    - cp doc public
    - npm run readme
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
