image: node:20.9.0

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install --frozen-lockfile

cache:
  paths:
    - .pnpm-store/

lint:
  script:
    - pnpm lint

test:
  script:
    - pnpm build
    - CI=true pnpm test

release:
  only:
    - tags
  script:
    - pnpm build
  artifacts:
    paths:
      - dist/src

pages:
  stage: deploy
  script:
    - pnpm doc
    - pnpm doc-simple:build
    - mkdir -p public
    - cp -r doc/* public/
    - cp -r simple-doc public/
    - cp badge-*.svg public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
