name: genFlowyThings
version: 0.1.0.0
license: AGPL-3
author: monnef
copyright: "2021 monnef"

dependencies:
  - base >= 4.7 && < 5
  - text
  - interpolatedstring-perl6
  - string-conv
  - safe


library:
  source-dirs: src

executables:
  genFlowyThings-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - genFlowyThings

tests:
  genFlowyThings-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - genFlowyThings
